In [1]:
import numpy as np

In [2]:
arr = [10, 100, 300, 400, 50, 4500, 200, 30, 90]

k=3

In [3]:
MVBLN = np.zeros((k+1,len(arr)))

In [4]:
MVBLN

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
MVBLN[0][0] = arr[0]
MVBLN[0][1] = max(arr[1], MVBLN[0][0])
for i in range(2,len(arr)):
    MVBLN[0][i] = max(MVBLN[0][i-1], MVBLN[0][i-2]+arr[i])

In [6]:
MVBLN

array([[  10.,  100.,  310.,  500.,  500., 5000., 5000., 5030., 5090.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]])

In [7]:
for m in range(k):
    MVBLN[m+1][0] = arr[0]
    MVBLN[m+1][1] = arr[1]+arr[0]

In [8]:
MVBLN

array([[  10.,  100.,  310.,  500.,  500., 5000., 5000., 5030., 5090.],
       [  10.,  110.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [  10.,  110.,    0.,    0.,    0.,    0.,    0.,    0.,    0.],
       [  10.,  110.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]])

In [9]:
for j in range(1,k+1):

    for m in range(2,len(arr)):
        MVBLN[j][m] = max(MVBLN[j][m-1], MVBLN[j-1][m-1]+arr[m], MVBLN[j][m-2]+arr[m])

In [10]:
MVBLN

array([[  10.,  100.,  310.,  500.,  500., 5000., 5000., 5030., 5090.],
       [  10.,  110.,  400.,  710.,  710., 5210., 5210., 5240., 5300.],
       [  10.,  110.,  410.,  800.,  800., 5300., 5410., 5410., 5500.],
       [  10.,  110.,  410.,  810.,  850., 5310., 5500., 5500., 5590.]])